server:
  port: 8090
person:
  id: 1
  name: tom
  age: 18
  sex: 男
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/spring
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
